### ISSUE TITLE
Improve Installation & Admin

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/doc-geonode#45]
- [ ] #46 Move section "VM Setup with VirtualBox" out of Linux Admin Intro
- [ ] #48 Move section "Running a VM with Vagrant" out of Linux Admin Intro
- [ ] #49 Move section "Running Ansible scripts" out of Linux Admin Intro
- [ ] #50 Add basic tutorial for CentOs
